Repository hashgraph/hedera-cli, pull requests merged in 2019-10, with the labels that each got.

#26 Feature/switch accounts
  .vscode/launch.json
  build.gradle
  src/main/java/com/hedera/cli/Application.java
  src/main/java/com/hedera/cli/HederaCrypto.java
  src/main/java/com/hedera/cli/HederaFile.java
  src/main/java/com/hedera/cli/hedera/Hedera.java
  src/main/java/com/hedera/cli/hedera/crypto/Account.java
  src/main/java/com/hedera/cli/hedera/crypto/AccountCreate.java
  src/main/java/com/hedera/cli/hedera/crypto/AccountDelete.java
  src/main/java/com/hedera/cli/hedera/crypto/AccountInfo.java
  src/main/java/com/hedera/cli/hedera/crypto/AccountList.java
  src/main/java/com/hedera/cli/hedera/crypto/AccountRecovery.java
  src/main/java/com/hedera/cli/hedera/crypto/AccountUpdate.java
  src/main/java/com/hedera/cli/hedera/crypto/AccountUse.java
  src/main/java/com/hedera/cli/hedera/crypto/CryptoTransfer.java
  src/main/java/com/hedera/cli/hedera/crypto/CryptoTransferMultiple.java
  src/main/java/com/hedera/cli/hedera/crypto/PicocliSpringFactory.java
  src/main/java/com/hedera/cli/hedera/crypto/Transfer.java
  src/main/java/com/hedera/cli/hedera/file/File.java
  src/main/java/com/hedera/cli/hedera/file/FileCreate.java
  src/main/java/com/hedera/cli/hedera/file/FileDelete.java
  src/main/java/com/hedera/cli/hedera/keygen/KeyGeneration.java
  src/main/java/com/hedera/cli/hedera/setup/Setup.java
  src/main/java/com/hedera/cli/hedera/utils/AccountUtils.java
  src/main/java/com/hedera/cli/hedera/utils/DataDirectory.java
  src/main/java/com/hedera/cli/hedera/utils/Utils.java
  src/main/java/com/hedera/cli/services/CurrentAccountService.java
  src/main/java/com/hedera/cli/shell/CliPromptProvider.java
  src/test/java/com/hedera/cli/hedera/HederaTest.java
  src/test/java/com/hedera/cli/hedera/botany/AdjectivesWordListTest.java
  src/test/java/com/hedera/cli/hedera/crypto/AccountUseTest.java
  src/test/java/com/hedera/cli/hedera/crypto/CryptoTransferMultipleTest.java
  src/test/java/com/hedera/cli/hedera/keygen/KeyGenerationTest.java
  src/test/java/com/hedera/cli/hedera/network/NetworkListTest.java
  src/test/java/com/hedera/cli/hedera/setup/SetupTest.java
  src/test/java/com/hedera/cli/hedera/utils/AccountUtilsTest.java
  src/test/java/com/hedera/cli/hedera/utils/DataDirectoryTest.java
  src/test/java/com/hedera/cli/services/CurrentAccountServiceTest.java
Labels: p1

#38 36 curl installer
  README.md
  install.sh
Labels: enhancement

#42 35 account info publickey
  src/main/java/com/hedera/cli/hedera/crypto/AccountList.java
  src/test/java/com/hedera/cli/hedera/crypto/AccountListTest.java
Labels: enhancement

#54 Fix broken commands
  build.gradle
  src/main/java/com/hedera/cli/hedera/Hedera.java
  src/main/java/com/hedera/cli/hedera/crypto/AccountDelete.java
  src/main/java/com/hedera/cli/hedera/crypto/AccountRecovery.java
  src/main/java/com/hedera/cli/hedera/crypto/AccountUse.java
  src/main/java/com/hedera/cli/hedera/setup/Setup.java
  src/main/java/com/hedera/cli/hedera/utils/DataDirectory.java
  src/test/java/com/hedera/cli/hedera/crypto/AccountListTest.java
  src/test/java/com/hedera/cli/hedera/crypto/AccountUseTest.java
Labels: bug, enhancement, p1

#55 For manual verification
  src/main/java/com/hedera/cli/Application.java
  src/main/java/com/hedera/cli/commands/GetStarted.java
  src/main/java/com/hedera/cli/hedera/network/Network.java
  src/main/java/com/hedera/cli/hedera/network/NetworkList.java
  src/main/java/com/hedera/cli/hedera/setup/Setup.java
  src/main/java/com/hedera/cli/hedera/utils/DataDirectory.java
  src/main/java/com/hedera/cli/models/AddressBookManager.java
  src/main/java/com/hedera/cli/models/Network.java
  src/main/java/com/hedera/cli/shell/CliPromptProvider.java
  src/main/resources/addressbook.json
Labels: bug, enhancement

#49 24 no comma between command options
  README.md
  build.gradle
  src/main/java/com/hedera/cli/Application.java
  src/main/java/com/hedera/cli/ExampleCommands.java
  src/main/java/com/hedera/cli/HederaCrypto.java
  src/main/java/com/hedera/cli/HederaFile.java
  src/main/java/com/hedera/cli/HederaNetwork.java
  src/main/java/com/hedera/cli/Initialise.java
  src/main/java/com/hedera/cli/Node.java
  src/main/java/com/hedera/cli/commands/GetStarted.java
  src/main/java/com/hedera/cli/commands/HederaConsensus.java
  src/main/java/com/hedera/cli/commands/HederaContract.java
  src/main/java/com/hedera/cli/commands/HederaCrypto.java
  src/main/java/com/hedera/cli/commands/HederaFile.java
  src/main/java/com/hedera/cli/commands/HederaKey.java
  src/main/java/com/hedera/cli/commands/HederaMirror.java
  src/main/java/com/hedera/cli/commands/HederaNetwork.java
  src/main/java/com/hedera/cli/defaults/CliDefaults.java
  src/main/java/com/hedera/cli/hedera/Hedera.java
  src/main/java/com/hedera/cli/hedera/crypto/Account.java
  src/main/java/com/hedera/cli/hedera/crypto/AccountCreate.java
  src/main/java/com/hedera/cli/hedera/crypto/AccountDelete.java
  src/main/java/com/hedera/cli/hedera/crypto/AccountGetInfo.java
  src/main/java/com/hedera/cli/hedera/crypto/AccountList.java
  src/main/java/com/hedera/cli/hedera/crypto/AccountRecovery.java
  src/main/java/com/hedera/cli/hedera/crypto/AccountUpdate.java
  src/main/java/com/hedera/cli/hedera/crypto/AccountUse.java
  src/main/java/com/hedera/cli/hedera/crypto/CryptoTransfer.java
  src/main/java/com/hedera/cli/hedera/crypto/CryptoTransferMultiple.java
  src/main/java/com/hedera/cli/hedera/crypto/Transfer.java
  src/main/java/com/hedera/cli/hedera/file/FileCreate.java
  src/main/java/com/hedera/cli/hedera/file/FileDelete.java
  src/main/java/com/hedera/cli/hedera/network/Network.java
  src/main/java/com/hedera/cli/hedera/network/NetworkList.java
  src/main/java/com/hedera/cli/hedera/network/NetworkSet.java
  src/main/java/com/hedera/cli/hedera/network/NetworkUse.java
  src/main/java/com/hedera/cli/hedera/setup/Setup.java
  src/main/java/com/hedera/cli/hedera/utils/AccountUtils.java
  src/main/java/com/hedera/cli/hedera/utils/DataDirectory.java
  src/main/java/com/hedera/cli/hedera/utils/Utils.java
  src/main/java/com/hedera/cli/models/AddressBook.java
  src/main/java/com/hedera/cli/models/AddressBookManager.java
  src/main/java/com/hedera/cli/models/HederaNode.java
  src/main/java/com/hedera/cli/models/Network.java
  src/main/java/com/hedera/cli/shell/CliPromptProvider.java
  src/main/resources/addressbook.json
  src/test/java/com/hedera/cli/hedera/HederaTest.java
  src/test/java/com/hedera/cli/hedera/crypto/AccountUseTest.java
  src/test/java/com/hedera/cli/hedera/network/NetworkListTest.java
  src/test/java/com/hedera/cli/hedera/setup/SetupTest.java
  src/test/java/com/hedera/cli/hedera/utils/AccountUtilsTest.java
  src/test/java/com/hedera/cli/hedera/utils/DataDirectoryTest.java
  src/test/java/com/hedera/cli/hedera/utils/UtilsTest.java
  src/test/java/com/hedera/cli/models/AddressBookTest.java
  src/test/java/com/hedera/cli/models/HederaNodeTest.java
  src/test/java/com/hedera/cli/models/NetworkTest.java
  src/test/java/com/hedera/cli/services/CurrentAccountServiceTest.java
Labels: enhancement, p1

#57 Merge user declared network with our default addressbook.json
  build.gradle
  src/main/java/com/hedera/cli/models/AddressBook.java
  src/main/java/com/hedera/cli/models/AddressBookManager.java
  src/main/resources/addressbook.hjson
  src/main/resources/addressbook.json
  src/main/resources/addressbook_unstructured.json
Labels: enhancement
